name: 'Weekly Release'

on:
  schedule:
    - cron:  '0 8 * * 1'
  workflow_dispatch:
jobs:
  weekly-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Get current date for tag
        id: date
        run: echo "TAG_DATE=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV
      - name: Tag & Push to Production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a ${{ env.TAG_DATE }} -m "release ${{ env.TAG_DATE }}"
          git push --follow-tags
          git push --force origin ${{ env.TAG_DATE }}:production
