name: 'Weekly Release'

on:
  schedule:
    - cron:  '0 8 * * 1'
  workflow_dispatch:
jobs:
  weekly-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Get current date for tag
        id: date
        run: echo "TAG_DATE=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV
      - name: Tag Release
        uses: ChloePlanet/github-tag-action@2.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ env.TAG_DATE }}
      - name: Push to Production
        run: |
          git push --force origin ${{ env.TAG_DATE }}:production
