name: 'Weekly Release'

on:
  schedule:
    - cron:  '0 8 * * 1'
  workflow_dispatch:
jobs:
  weekly-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date for tag
        id: date
        run: echo "TAG_DATE=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV
      - name: Tag & Release master -> production
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          custom_tag: ${{ env.TAG_DATE }}
