name: 'Release'

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  weekly-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: untappd/utc-release-action@2021.01.15.191524
        name: Tag & Push to Production
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

