name: 'Weekly Release'

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  weekly-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Get current date for tag
        id: date
        run: echo "TAG_DATE=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV
      - uses: ./action-release
        name: Tag & Push to Production
        with:
          tag_name: ${{ env.TAG_DATE }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
