name: 'Weekly Release'

on:
  schedule:
    - cron:  '0 8 * * 1'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Level'     
        required: true
        default: 'warning'
      tags:
        description: 'Tag release' 
jobs:
  weekly-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Merge master -> production
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: master
        target_branch: production

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
